export const CREATE_PRODUCT = 'CREATE_PRODUCT'
export const READ_PRODUCT = 'READ_PRODUCT'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'

export const READ_PRODUCTS = 'READ_PRODUCTS'
export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS'
export const DELETE_PRODUCTS = 'DELETE_PRODUCTS'
