export const CREATE_DEPARTMENT = 'CREATE_DEPARTMENT'
export const READ_DEPARTMENT = 'READ_DEPARTMENT'
export const UPDATE_DEPARTMENT = 'UPDATE_DEPARTMENT'
export const DELETE_DEPARTMENT = 'DELETE_DEPARTMENT'

export const READ_DEPARTMENTS = 'READ_DEPARTMENTS'
